Repository Instant-Visio/InstantVisio-WebApp, pull requests merged in 2021-01, with the labels that each got.

#457 Api: reminder cron
  firestore.indexes.json
  functions/src/api/index.ts
  functions/src/api/v1/invite/inviteParticipants.ts
  functions/src/callable/newCall.ts
  functions/src/cron/remindersCron.ts
  functions/src/cron/test.http
  functions/src/db/ReminderDao.ts
  functions/src/db/RoomDao.ts
  functions/src/index.ts
  functions/src/notifications/sendNotification.ts
  functions/src/notifications/sendNotifications.ts
  functions/src/translations.json
  functions/src/types/Notification.ts
  functions/src/types/Reminder.ts
Labels: api

#518 API : timezone on room + reminders
  functions/package-lock.json
  functions/package.json
  functions/src/api/swaggerDefinition.ts
  functions/src/api/v1/group/createGroup.ts
  functions/src/api/v1/rooms/createRoom.ts
  functions/src/api/v1/rooms/editRoom.ts
  functions/src/api/v1/rooms/getRooms.ts
  functions/src/cron/remindersCron.ts
  functions/src/db/RoomDao.ts
  functions/src/notifications/sendNotification.ts
  functions/src/notifications/sendNotifications.ts
  functions/src/types/Notification.ts
  functions/src/types/Room.ts
Labels: api

#520 Update README.md
  README.md
  public/instantvisio.png
Labels: documentation

#522 API: improve getToken and always save hostName
  functions/src/api/errors/HttpError.ts
  functions/src/api/v1/rooms/createRoom.ts
  functions/src/callable/getToken.ts
  functions/src/db/UserDao.ts
  functions/src/triggers/onUserCreation.ts
Labels: api

#523 API: fix timezone, improve twilio room creation & fix token generation JIT + some front removall
  functions/src/api/errors/HttpError.ts
  functions/src/api/v1/invite/inviteParticipants.ts
  functions/src/api/v1/rooms/createRoom.ts
  functions/src/api/v1/rooms/joinRoom.ts
  functions/src/constants.ts
  functions/src/notifications/sendNotifications.ts
  functions/src/triggers/onUserCreation.ts
  functions/src/types/NewRoomResponse.ts
  functions/src/types/Room.ts
  src/actions/getJwtToken.ts
Labels: api, bug, enhancement

#567 Fix editRoom not working
  src/services/api.ts
Labels: webApp

#576 Fix toggle btn
  public/locales/en/dashboard.json
  public/locales/en/join-group-form.json
  public/locales/fr/dashboard.json
  src/pages/AdminDashboard/CreateRoomForm/CreateRoomForm.tsx
  src/pages/AdminDashboard/roomsActions.ts
Labels: webApp

#583 API: add reminders edit on editRoom, fix createGroup and add startAt on push data
  functions/src/api/v1/group/createGroup.ts
  functions/src/api/v1/rooms/createRoom.ts
  functions/src/api/v1/rooms/editRoom.ts
  functions/src/api/v1/rooms/parseSendsAt.ts
  functions/src/api/v1/rooms/service/makeParticipantNameUnique.ts
  functions/src/db/ReminderDao.ts
  functions/src/notifications/sendNotifications.ts
Labels: api

#586 API Fix string on push data
  functions/src/api/v1/rooms/createRoom.ts
  functions/src/constants.ts
  functions/src/notifications/sendNotifications.ts
  functions/src/notifications/sendPush.ts
Labels: api, bug

#587 Make ip pool name optional
  functions/src/firebase/env.ts
  functions/src/types/SendGridEnv.ts
Labels: bug

#594 Add two channel and manage them for push notif
  android/app/build.gradle
  android/app/src/main/res/values/strings.xml
  functions/src/cron/remindersCron.ts
  functions/src/notifications/sendNotifications.ts
  functions/src/notifications/sendPush.ts
  functions/src/types/Notification.ts
  package.json
  src/services/local-notifications.ts
  src/services/push-notifications.ts
Labels: api, enhancement

#602 Front: fix startAt new room + edit buttons + timezone
  package-lock.json
  src/pages/AdminDashboard/AdminDashboard.tsx
  src/pages/AdminDashboard/CreateRoomForm/CreateRoomForm.tsx
  src/pages/AdminDashboard/roomsActions.ts
  src/pages/PremiumVideoCall/index.tsx
  src/services/api.ts
Labels: bug, webApp

#604 Fix getGroups missing and remove autoComplete on join group and participants
  src/components/CreateGroup/CreateGroupForm.tsx
  src/components/JoinGroup/JoinGroupForm.tsx
  src/components/Lang/config.json
  src/pages/AdminDashboard/AdminDashboard.tsx
  src/pages/AdminDashboard/CreateRoomForm/InviteParticipantsField.tsx
Labels: bug
